### ISSUE TITLE
discord-akairo (Botframework) einbinden

### ISSUE THREAD

**Issue by tygore587** [tygore587/DiscordBirthdayBot#1]
https://github.com/discord-akairo/discord-akairo

Es ist ein Botframework, welches einem viel Arbeit des selber bauens abnimmt. Einfach mal gucken, wie gut es funktioniert

**Comment by easylite376** [comment]
aktueller fortschritt:

https://discord-akairo.github.io/#/docs/main/stable/commands/prefixes

**Comment by tygore587** [comment]
done
